name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-backend-api:
    name: Build backend-api image
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.ACTIONS_USERNAME }}
          password: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: ./apps/backend/Dockerfile
          push: true
          tags: ghcr.io/swe3028-41-team-g/skkudm-api:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-backend-api]
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.2

      - name: Create Terraform variable file
        working-directory: ./apps/aws
        run: |
          echo "$TFVARS" >> terraform.tfvars
        env:
          TFVARS: ${{ secrets.TFVARS }}

      - name: Terraform Init
        working-directory: ./apps/aws
        run: terraform init

      - name: Terraform Plan
        working-directory: ./apps/aws
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ./apps/aws
        run: terraform apply -auto-approve -input=false
