name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm --filter="backend" exec prisma generate

      - name: Build
        run: pnpm --filter="backend" build ${{ matrix.target }}

  build-backend-api:
    name: Build backend-api image
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.ACTIONS_USERNAME }}
          password: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: ./apps/backend/Dockerfile
          push: false
          tags: ghcr.io/swe3028-41-team-g/skkudm-api:latest

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:1234@127.0.0.1:5432/skkudm?schema=public

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: skkudm

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check Prisma Migration
        run: |
          pnpm --filter="backend" exec prisma migrate diff \
            --from-migrations ./prisma/migrations \
            --to-schema-datamodel ./prisma/schema.prisma \
            --shadow-database-url ${{ env.DATABASE_URL }} \
            --exit-code ||
          (echo "::error::Prisma migration is not up to date." \
          "Please run 'pnpm prisma migrate dev' locally and commit the changes." && exit 1)

      - name: Migrate Prisma
        run: pnpm --filter="backend" exec prisma migrate reset --force

      - name: Test
        run: pnpm --filter="backend" test
